version: '3.8'

services:
  testing_build_app:
    container_name: testing_build_app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    environment:
      - DB_URI=mongodb://root:pass12345@host.docker.internal:27017/?directConnection=true&tls=false
      - AWS_URL=http://host.docker.internal:9000
      - AWS_ENDPOINT=http://host.docker.internal:9000

  k_web:
    image: nginx:1.20-alpine
    ports:
      - 8081:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - testing_build_app